if(NOT DEFINED INPUTS OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOLS)
  message(FATAL_ERROR "EmbedBinary.cmake requires INPUTS, OUTPUT, and SYMBOLS")
endif()

string(REPLACE "|" ";" input_list "${INPUTS}")
string(REPLACE "|" ";" symbol_list "${SYMBOLS}")
list(LENGTH input_list input_count)
list(LENGTH symbol_list symbol_count)
if(NOT input_count EQUAL symbol_count)
  message(FATAL_ERROR "INPUTS and SYMBOLS must have matching lengths")
endif()

file(WRITE "${OUTPUT}" "#pragma once\n#include <cstddef>\nnamespace morph_bridge::shaders {\n")
math(EXPR last_index "${input_count} - 1")
foreach(index RANGE ${last_index})
  list(GET input_list ${index} input)
  list(GET symbol_list ${index} symbol)
  file(READ "${input}" binary_hex HEX)
  string(LENGTH "${binary_hex}" binary_hex_length)
  math(EXPR binary_size "${binary_hex_length} / 2")
  string(REGEX REPLACE "(..)" "0x\\1," binary_bytes "${binary_hex}")
  file(APPEND "${OUTPUT}"
    "inline constexpr unsigned char ${symbol}[] = {${binary_bytes}};\ninline constexpr std::size_t ${symbol}_size = ${binary_size};\n")
endforeach()
file(APPEND "${OUTPUT}" "}  // namespace morph_bridge::shaders\n")
